version: '3'

services:

#======= NGINX =======#
  nginx:
    # init: true
    depends_on:
      - wordpress
      - mariadb
    build: 
      context: ./requirements/nginx
    ports:
      - 443:443
    container_name: nginx
    restart: always
    networks:
      - docker-network
    volumes:
      - php_nginx:/var/www/html
    env_file:
      - .env

#===== WORDPRESS =====#
  wordpress:
    # init: true
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
    ports:
      - 9000:9000
    container_name: wordpress
    restart: always
    networks:
      - docker-network
    env_file:
      - .env
    volumes:
      - php_nginx:/var/www/html


#====== MARIADB ======#
  mariadb:
    # init: true
    build: 
      context: ./requirements/mariadb
    ports:
      - 3306:3306
    container_name: mariadb
    restart: always
    networks:
      - docker-network
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

# NETWORKS #

networks:
  docker-network:

# VOLUMES #

volumes:

  php_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ade-la-c/data/php_nginx

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ade-la-c/data/database
